### ISSUE TITLE
Issues decompiling apps

### ISSUE THREAD

**Issue by Razican** [SUPERAndroidAnalyzer/super#42]
Using Java dependencies is causing decompilation errors. This should be fixed when we implement #22. Some of the errors are shown here:

With `com.google.android.apps.photos`:

```
Error: The decompression command returned an error. More info: Exception in thread "main" java.lang.NullPointerException
    at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:58)
    at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:516)
    at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:267)
    at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
    at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
    at brut.apktool.Main.cmdDecode(Main.java:163)
    at brut.apktool.Main.main(Main.java:81)
```

With `com.alibaba.aliexpresshd`:

```
Error: The decompression command returned an error. More info: Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
    at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
    at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:558)
    at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
    at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
    at brut.androlib.Androlib.getResTable(Androlib.java:67)
    at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:193)
    at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
    at brut.apktool.Main.cmdDecode(Main.java:163)
    at brut.apktool.Main.main(Main.java:81)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000001
    at brut.util.ExtDataInput.skipCheckChunkTypeInt(ExtDataInput.java:75)
    at brut.util.ExtDataInput.skipCheckChunkTypeInt(ExtDataInput.java:73)
    at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:44)
    at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:75)
    at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
    ... 8 more
```

And a possibly unrelated issue in `com.google.android.apps.fireball`:

```
Error: There was an error when decompressing the .apk file. More info: Io Error: Could not read enough bytes
```

**Comment by Razican** [comment]
The first two are APKTool related. I will create issues in upstream repo. The last one needs more testing and some troubleshooting. In any case first two are not really up to us until we fix #20. I'm removing the milestone.

**Comment by Razican** [comment]
@gnieto could you check if this is still happening? The third issue seems unrelated and should probably have its own issue, but if the other two are fixed we can close this issue.

**Comment by gnieto** [comment]
Solved the issue with `com.google.android.apps.photos` on develop. `com.alibaba.aliexpresshd` also can be decompressed, but now fails converting DEX to JAR
I will create a new issue to track issues converting DEX to JAR.
